--
-- Create Schema Script
--   Database Version            : 12.2.0.1.0

-- "Set define off" turns off substitution variables.
Set define off; 

--
-- drop soe schema and tablespace (if they already exist)
--
DROP USER soe CASCADE;

DROP TABLESPACE SOETBS INCLUDING CONTENTS AND DATAFILES;

@/u01/app/oracle/product/12.2.0/db_1/sqlplus/admin/plustrce.sql

--
-- SOETBS  (Tablespace) 
--
CREATE TABLESPACE SOETBS DATAFILE 
   SIZE 879M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED
LOGGING
DEFAULT 
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
SEGMENT SPACE MANAGEMENT AUTO;

--
-- SOE  (User) 
--
CREATE USER SOE
  IDENTIFIED BY soe
  DEFAULT TABLESPACE SOETBS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;


ALTER USER SOE QUOTA UNLIMITED ON SOETBS;
ALTER USER SYSTEM QUOTA UNLIMITED ON SOETBS;
ALTER USER SYS QUOTA UNLIMITED ON SOETBS;


--
-- CONNECT  (Role) 
--
GRANT CONNECT TO SOE;
--
-- PLUSTRACE  (Role) 
--
GRANT PLUSTRACE TO SOE;
--
-- RESOURCE  (Role) 
--
GRANT RESOURCE TO SOE;
ALTER USER SOE DEFAULT ROLE ALL;

-- System Privileges for SOE 
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'SOE', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
GRANT ALTER SESSION TO SOE;
GRANT ALTER SYSTEM TO SOE;
GRANT ANALYZE ANY TO SOE;
GRANT ANALYZE ANY DICTIONARY TO SOE;
GRANT CREATE JOB TO SOE;
GRANT CREATE VIEW TO SOE;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'SOE',
  ADMIN_OPTION => FALSE);
END;
/
GRANT MANAGE SCHEDULER TO SOE;

-- Further grants to soe:
GRANT SELECT ON V_$PARAMETER to soe;
GRANT SELECT ON V_$SESSION TO SOE;
GRANT SELECT ON V_$SQL_PLAN_STATISTICS_ALL TO SOE;
GRANT SELECT ON V_$SQL TO SOE;
GRANT SELECT ON V_$SQL_PLAN TO SOE;
GRANT SELECT ON V_$SQL_SHARED_CURSOR TO SOE;
GRANT SELECT ON V_$SQL TO SOE;
GRANT SELECT ON V_$PROCESS TO SOE;
GRANT SELECT ON V_$MYSTAT TO SOE;
GRANT SELECT ON V_$SQL TO SOE;
GRANT SELECT ON V_$SQL_BIND_CAPTURE TO SOE;
GRANT SELECT ON V_$SQLAREA TO SOE;
GRANT SELECT ON V_$SQLAREA_PLAN_HASH TO SOE;
GRANT SELECT ON V_$SQLSTATS TO SOE;
GRANT SELECT ON V_$RESULT_CACHE_OBJECTS TO SOE;
GRANT SELECT ON SYS.COL_USAGE$ TO SOE;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO SOE;
GRANT ADVISOR TO SOE;
GRANT ADMINISTER ANY SQL TUNING SET TO SOE;
GRANT ADMINISTER SQL TUNING SET TO SOE;
GRANT ADMINISTER SQL MANAGEMENT OBJECT to SOE;
GRANT CREATE MATERIALIZED VIEW TO soe;
GRANT EXECUTE ON DBMS_ADVANCED_REWRITE TO soe;
GRANT EXECUTE ON SYS.DBMS_LOCK TO SOE;
GRANT SELECT ON SYS.V_$PARAMETER TO SOE;
GRANT EXECUTE ON SYS.SYS_PLSQL_D9B1149D_9_1 TO SOE WITH GRANT OPTION;
GRANT EXECUTE ON SYS.SYS_PLSQL_FAA5F685_2385_1 TO SOE WITH GRANT OPTION;

impdp  directory=datapump dumpfile=soe.dmp

/ as sysdba