sqlplus / as sysdba

SHOW PARAMETER OPTIMIZER_MODE
Default is ALL_ROWS

===================
sqlplus soe/soe

SET LINESIZE 180
SET AUTOT TRACE EXP
SELECT /* ORIGINAL */ ORDER_ID FROM ORDERS;

SET LINESIZE 150
col SQL_TEXT format A60
SELECT OPTIMIZER_MODE, SUBSTR(SQL_TEXT,1,60) SQL_TEXT
FROM V$SQL
WHERE SQL_TEXT LIKE '%ORIGINAL%ORDERS%';


SELECT /*+ FIRST_ROWS */ /* MYTEST */ ORDER_ID FROM ORDERS;

SET LINESIZE 150
col SQL_TEXT format A60
SELECT OPTIMIZER_MODE, SUBSTR(SQL_TEXT,1,60) SQL_TEXT
FROM V$SQL
WHERE SQL_TEXT LIKE '%MYTEST%ORDERS%';

========================

set autot trace exp

SELECT 
DEPT_NO, DNAME
FROM DEPT D WHERE DEPT_NO=10;  ---INDEX UNIQUE SCAN

SELECT /*+ FULL(D) */
DEPT_NO, DNAME
FROM DEPT D WHERE DEPT_NO=10;

FULL
====
set lines 180
SELECT EMP_NO, ENAME, SALARY
FROM EMP E WHERE EMP_NO=635;

SELECT /*+ FULL(E) */ EMP_NO, ENAME, SALARY
FROM EMP E WHERE EMP_NO=635;

INDEX
======
SELECT /*+ INDEX(E INDEX_PK) */ EMP_NO, ENAME, SALARY
FROM EMP E WHERE EMP_NO=635;

NO_INDEX
========
SELECT 
EMP_NO, ENAME, SALARY
FROM EMP E WHERE EMP_NO BETWEEN 600 AND 610 AND DEPT_NO=60;  ---INDEX RANGE SCAN

SELECT /*+ NO_INDEX (E EMP_PK ) */
EMP_NO, ENAME, SALARY
FROM EMP E WHERE EMP_NO BETWEEN 600 AND 610 AND DEPT_NO=60;

INDEX_FFS
==========

CREATE INDEX EMP_ENAME_JC_IX ON EMP(ENAME, JOB_CODE) COMPUTE STATISTICS;

SELECT 
ENAME, JOB_CODE
FROM EMP E
WHERE ENAME LIKE 'Z%';  --- INDEX RANGE SCAN

SELECT /*+ INDEX_FFS(E EMP_ENAME_JC_IX) */
ENAME, JOB_CODE
FROM EMP E
WHERE ENAME LIKE 'Z%';


DROP INDEX EMP_ENAME_JC_IX;

LEADING 
=======

SELECT 
E.EMP_NO, E.ENAME, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPT_NO = D.DEPT_NO;

SELECT /*+ ORDERED FULL(E) FULL(D) */
E.EMP_NO, E.ENAME, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPT_NO = D.DEPT_NO;

SELECT /*+ LEADING(DEPT) FULL(EMP) FULL(DEPT) FULL(JOBS) */
 EMP_NO,ENAME,DNAME,JOB_NAME
FROM DEPT, EMP, JOBS
WHERE DEPT.DEPT_NO = EMP.DEPT_NO AND JOBS.JOB_CODE = EMP.JOB_CODE;

SELECT /*+ LEADING(EMP) FULL(EMP) FULL(DEPT) FULL(JOBS) */
 EMP_NO,ENAME,DNAME,JOB_NAME
FROM DEPT, EMP, JOBS
WHERE DEPT.DEPT_NO = EMP.DEPT_NO AND JOBS.JOB_CODE = EMP.JOB_CODE;


JOIN METHODS:
=============

SELECT /*+ USE_NL(EMP) */
EMP_NO,ENAME,DNAME
FROM EMP, DEPT
WHERE DEPT.DEPT_NO = EMP.DEPT_NO AND EMP_NO=630;

SELECT /*+ USE_HASH(DEPT) */
EMP_NO,ENAME,DNAME
FROM EMP, DEPT
WHERE DEPT.DEPT_NO = EMP.DEPT_NO AND EMP_NO=630;

SELECT /*+ USE_MERGE(JOBS) USE_MERGE(DEPT) */
EMP_NO,ENAME,DNAME,JOB_NAME
FROM EMP, DEPT, JOBS
WHERE DEPT.DEPT_NO = EMP.DEPT_NO AND JOBS.JOB_CODE = EMP.JOB_CODE;

PARALLEL
NOPARALLEL
============

SELECT * FROM EMP;

SELECT /*+ PARALLEL(EMP,5) */  * FROM EMP;
